### ISSUE TITLE
ux: "browse another project"

### ISSUE THREAD

**Issue by q9f** [ethb3rlin/Submi-ions#4]
currently, judges cannot see anything before the event is over.

before judging starts, it would be nice that a judge can randomly browse projects/teams (like hackers can).

but also have a header banner that says, "come back when judging starts at 14:00" or something like that.

**Comment by kirushik** [comment]
Closed via https://github.com/ethb3rlin/Submi-ions/commit/61938a1c11ce06d388239f8af8337062a16a0e93
